[package]
name = "smart-dataset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
async-trait = "0.1.58"
serde = { version = "1.0.147", features = ["derive"] }
